dummy: null
dset:
  musdb: ./dataset/label_noise
  musdb_samplerate: 44100
  wav: null
  wav2: null
  segment: 11
  shift: 1
  train_valid: false
  full_cv: true
  samplerate: 44100
  channels: 2
  normalize: true
  metadata: ./metadata
  sources:
  - drums
  - bass
  - other
  - vocals
  valid_samples: null
test:
  save: false
  best: true
  workers: 2
  every: 500000
  split: true
  shifts: 1
  overlap: 0.25
  sdr: true
  metric: nsdr
  nonhq: ../../../dataset/label_noise/
epochs: 200
batch_size: 32
max_batches: null
optim:
  lr: 0.0001
  momentum: 0.9
  beta2: 0.999
  loss: l1_trunc
  optim: adam
  weight_decay: 0
  clip_grad: 0
  trunc_ratio: 0.5
seed: 42
debug: false
valid_apply: true
flag: null
save_every: null
weights:
- 1.0
- 1.0
- 1.0
- 1.0
augment:
  shift_same: false
  repitch:
    proba: 0.2
    max_tempo: 12
  remix:
    proba: 1
    group_size: 4
  scale:
    proba: 1
    min: 0.25
    max: 1.25
  flip: true
continue_from: 32200d05
continue_pretrained: null
pretrained_repo: null
continue_best: true
continue_opt: false
misc:
  num_workers: 10
  num_prints: 10
  show: false
  verbose: false
ema:
  epoch: []
  batch: []
use_train_segment: true
model_segment: null
model: htdemucs
demucs:
  channels: 64
  growth: 2
  depth: 6
  rewrite: true
  lstm_layers: 0
  kernel_size: 8
  stride: 4
  context: 1
  gelu: true
  glu: true
  norm_groups: 4
  norm_starts: 4
  dconv_depth: 2
  dconv_mode: 1
  dconv_comp: 4
  dconv_attn: 4
  dconv_lstm: 4
  dconv_init: 0.0001
  resample: true
  normalize: false
  rescale: 0.1
hdemucs:
  channels: 48
  channels_time: null
  growth: 2
  nfft: 4096
  wiener_iters: 0
  end_iters: 0
  wiener_residual: false
  cac: true
  depth: 6
  rewrite: true
  hybrid: true
  hybrid_old: false
  multi_freqs: []
  multi_freqs_depth: 3
  freq_emb: 0.2
  emb_scale: 10
  emb_smooth: true
  kernel_size: 8
  stride: 4
  time_stride: 2
  context: 1
  context_enc: 0
  norm_starts: 4
  norm_groups: 4
  dconv_mode: 1
  dconv_depth: 2
  dconv_comp: 4
  dconv_attn: 4
  dconv_lstm: 4
  dconv_init: 0.001
  rescale: 0.1
torch_hdemucs:
  channels: 48
  growth: 2
  nfft: 4096
  depth: 6
  freq_emb: 0.2
  emb_scale: 10
  emb_smooth: true
  kernel_size: 8
  stride: 4
  time_stride: 2
  context: 1
  context_enc: 0
  norm_starts: 4
  norm_groups: 4
  dconv_depth: 2
  dconv_comp: 4
  dconv_attn: 4
  dconv_lstm: 4
  dconv_init: 0.001
htdemucs:
  channels: 48
  channels_time: null
  growth: 2
  nfft: 4096
  wiener_iters: 0
  end_iters: 0
  wiener_residual: false
  cac: true
  depth: 4
  rewrite: true
  multi_freqs: []
  multi_freqs_depth: 3
  freq_emb: 0.2
  emb_scale: 10
  emb_smooth: true
  kernel_size: 8
  stride: 4
  time_stride: 2
  context: 1
  context_enc: 0
  norm_starts: 4
  norm_groups: 4
  dconv_mode: 1
  dconv_depth: 2
  dconv_comp: 8
  dconv_init: 0.001
  bottom_channels: 0
  t_layers: 5
  t_hidden_scale: 4.0
  t_heads: 8
  t_dropout: 0.0
  t_layer_scale: true
  t_gelu: true
  t_emb: sin
  t_max_positions: 10000
  t_max_period: 10000.0
  t_weight_pos_embed: 1.0
  t_cape_mean_normalize: true
  t_cape_augment: true
  t_cape_glob_loc_scale:
  - 5000.0
  - 1.0
  - 1.4
  t_sin_random_shift: 0
  t_norm_in: true
  t_norm_in_group: false
  t_group_norm: false
  t_norm_first: true
  t_norm_out: true
  t_weight_decay: 0.0
  t_lr: null
  t_sparse_self_attn: false
  t_sparse_cross_attn: false
  t_mask_type: diag
  t_mask_random_seed: 42
  t_sparse_attn_window: 400
  t_global_window: 100
  t_sparsity: 0.95
  t_auto_sparsity: false
  t_cross_first: false
  rescale: 0.1
svd:
  penalty: 0
  min_size: 0.1
  dim: 1
  niters: 2
  powm: false
  proba: 1
  conv_only: false
  convtr: false
  bs: 1
quant:
  diffq: null
  qat: null
  min_size: 0.2
  group_size: 8
dora:
  dir: outputs
  exclude:
  - misc.*
  - slurm.*
  - test.reval
  - flag
slurm:
  time: 4320
  constraint: volta32gb
  setup:
  - module load cudnn/v8.4.1.50-cuda.11.6 NCCL/2.11.4-6-cuda.11.6 cuda/11.6
